name: "Build and push docker"

on: 
  workflow_dispatch:
    inputs:
      tag:
        description: docker image tag


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub Registry
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
      - name: Get image tag
        run: echo ${{ github.event.inputs.tag }}

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: ./grafana
          push: true
          tags: asukiasyanst/grafana:${{ github.event.inputs.tag }}

