name: Package

on:
  push:
    branches: [ main ]
  
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PACKAGE_VERSION: version on the JOB level
      FILE_MODE: 777      

    steps:
      - uses: actions/checkout@v2

      - name: Export the command to the env file
        run: echo "COMMAND= -pm "${{ env.FILE_MODE }}"" >> $GITHUB_ENV

      - name: Echo github_env
        run: echo $GITHUB_ENV

      - name: Read the command
        run: echo $COMMAND

      - name: mkdir with variable param
        run: mkdir $COMMAND testdir/nestdir

      - name: Verify that the dir was created
        run: ls -la testdir

      # - name: Read the job level env variable
      #   run: echo "${{ env.PACKAGE_VERSION }}"

      # - name: Read the step level env variable
      #   env:
      #     PACKAGE_VERSION: version on the STEP level
      #   run: echo "${{ env.PACKAGE_VERSION }}"

      # - name: execute step if the event is push
      #   if: github.event_name  == 'push'
      #   run: echo "${{ github.event_name }}"

      # - name: skip the step if the event is push
      #   if: github.event_name  != 'push'
      #   run: echo "${{ github.event_name }}"

      

      
