name: Deploy

on:
  workflow_run:
    workflows: 
      - Package
    branches: [main]
    types: 
      - completed
  


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PACKAGE_VERSION: 0.0.1

    steps:
      - uses: actions/checkout@v2

      - name: Read the job level env variable
        run: echo "${{ env.PACKAGE_VERSION }}"

      - name: Read the step level env variable
        env:
          PACKAGE_VERSION: 0.0.2
        run: echo "${{ env.PACKAGE_VERSION }}"
