name: Deploy

on:
  workflow_run:
    workflows: 
      - Package
    branches: [main]
    types: 
      - completed
  


jobs:
  build:
    runs-on: ubuntu-latest    

    steps:
      - uses: actions/checkout@v2

      - name: Write env variable to github_env file
        run: echo "PACKAGE_VERSION=1.0.0" >> $GITHUB_ENV

      - name: Read the env variable from the file        
        run: echo "${{ PACKAGE_VERSION }}"
